name: Docker Image CI

on:
  push:
    branches: master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Login to DockerHub Registry
            run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          - name: Build the latest Docker image
            run: docker build -t screetsec/sudomy:v1.1.9
          - name: Push the latest Docker image
            run: docker push screetsec/sudomy:v1.1.9
